name: Testing stuff

on:
  push:
    branches:
      - master

env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  COMMIT_STRING: ${{ join(env.COMMIT_MESSAGES) }}
  SKIP_DEPLOY: ${{ contains(env.COMMIT_STRING, '#skip') }}

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        run:
          echo "$env.COMMIT_MESSAGES"
          echo "$env.COMMIT_STRING"
          echo "$env.SKIP_DEPLOY"
