name: Testing stuff

on:
  push:
    branches:
      - master

env:
  SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # - name: gihub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      # - name: commits
      #   env:
      #     COMMITS: ${{ toJson(github.event.commits) }}
      #   run: echo "$COMMITS"
      - name: commit messages
        if: ${{ !SKIP_DEPLOY }}
        # env:
        #   COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        #   COMMIT_STRING: ${{ join(github.event.commits.*.message) }}
        #   SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run:
          # echo "$COMMIT_MESSAGES"
          # echo "$COMMIT_STRING"
          echo "$SKIP_DEPLOY"
